[versions]
# Android setup
sdk-compile = "32"
sdk-min = "23"
sdk-target = "32"

# Plugins
android = "7.2.1"
kotlin = "1.7.10"

# Libraries
retrofit = "2.9.0"
okhttp-logging-interceptor = "4.10.0"
kodein = "7.2.0"
glide = "4.13.2"
core-ktx = "1.8.0"
appcompat = "1.4.2"
constraintlayout = "2.1.4"
lifecycle = "2.2.0"
oss-licenses = "17.0.0"
oss-licenses-plugin = "0.10.5"
leakcanary = "2.9.1"

# Testing
junit = "4.13.2"
junit-ui-test = "1.1.3"
espresso = "3.4.0"

[plugins]
application = { id = "com.android.application", version.ref = "android" }
library = { id = "com.android.library", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
oss-licenses = { id = "com.google.android.gms:oss-licenses-plugin", version.ref = "oss-licenses-plugin" }

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }
kodein = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
lifecycle-ext = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "oss-licenses" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }

# Annotations
annotation-glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }

# UI testing
junit-ui = { module = "androidx.test.ext:junit", version.ref = "junit-ui-test" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }