[versions]
# Android setup
sdk-compile = "32"
sdk-min = "23"
sdk-target = "32"

# Plugins
android = "7.2.1"
kotlin = "1.7.10"
detekt = "1.20.0"
kotlinter = "3.11.1"
dagger = "2.42"

# Libraries
retrofit = "2.9.0"
okhttp-logging-interceptor = "4.10.0"
glide = "4.13.2"
core-ktx = "1.8.0"
appcompat = "1.4.2"
constraintlayout = "2.1.4"
lifecycle = "2.2.0"
oss-licenses = "17.0.0"
oss-licenses-plugin = "0.10.5"
leakcanary = "2.9.1"
ktx = "1.5.0"

# Testing
espresso = "3.4.0"

[plugins]
application = { id = "com.android.application", version.ref = "android" }
library = { id = "com.android.library", version.ref = "android" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
oss-licenses = { id = "com.google.android.gms:oss-licenses-plugin", version.ref = "oss-licenses-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging-interceptor" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
lifecycle-ext = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
oss-licenses = { module = "com.google.android.gms:play-services-oss-licenses", version.ref = "oss-licenses" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "ktx"}
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "ktx"}

# Dagger
dagger-hilt = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
dagger-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "dagger" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "dagger" }
dagger-hilt-androidx = { module = "androidx.hilt:hilt-compiler", version = "1.0.0" }

# Annotations
annotation-glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Testing
junit5-bom = { module = "org.junit:junit-bom", version = "5.8.2" }
junit5 = { module = "org.junit.jupiter:junit-jupiter" }
junit4 = { module = "junit:junit", version = "4.13.2" }

# UI testing
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }