[versions]
# Android setup
sdk-compile = "32"
sdk-min = "23"
sdk-target = "32"

# Plugins
gradle = "7.2.1"
kotlin = "1.3.72"

# Libraries
retrofit = "2.9.0"
retrofit-logging-interceptor = "4.8.0"
kodein = "7.0.0"
glide = "4.13.2"
core-ktx = "1.1.0"
appcompat = "1.1.0"
constraint-layout = "1.1.3"
lifecycle = "2.1.0"

# Testing
junit = "4.13.2"
android-test-ext = "1.1.1"
espresso = "3.2.0"
junit-ui-test = "1.1.1"

[plugins]
gradle = { id = "com.android.tools.build:gradle", version.ref = "gradle" }
kotlin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[libraries]
kotlin = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "retrofit-logging-interceptor" }
kodein = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraint-layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint-layout" }
lifecycle-ext = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }

# Annotations
annotation-glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Testing
junit = { module = "junit:junit", version.ref = "junit" }

# UI testing
junit-ui = { module = "androidx.test.ext:junit", version.ref = "junit-ui-test" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }