name: Run Android lint

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build App
        run: ./gradlew lint

      - uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/reports/lint-results-debug.html