#name: UI tests
#
#on:
#  push:
#    branches: [main]
#  pull_request:
#    types: [opened, synchronize]
#
#jobs:
#  build:
#    runs-on: macos-13 # emulator never starts on macOS 14 https://github.com/ReactiveCircus/android-emulator-runner/issues/392#issuecomment-2106167725
#    steps:
#      - name: checkout
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Run UI tests
#        uses: ReactiveCircus/android-emulator-runner@v2.30.1
#        with:
#          api-level: 29
#          target: default
#          arch: x86
#          profile: Nexus 6
#          disable-animations: true
#          script: ./gradlew connectedCheck
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: ui-test-results.zip
#          path: ./**/build/reports/ui-tests/