name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run unit tests
        run: ./gradlew test

      - name: Generate Kover reports
        run: ./gradlew :app:koverXmlReportDebug :app:koverVerify

      - name: Upload Kover failed coverage reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: kover-error-report
          path:
              app/build/reports/kover/verify.err

      - uses: actions/upload-artifact@v4
        with:
          name: unit-test-results.zip
          path: ./**/build/reports/tests/

      - name: Upload coverage reports to Codecov
        if: always()
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
          files: app/build/reports/kover/reportDebug.xml
          verbose: true